name: CommunityMinecraftPlugin
main: io.github.communityminecraftplugin.communityminecraftplugin.Core
version: 0.0.1-SNAPSHOT
description: Hello world!
commands:
  helloworld:
    description: Hello, world!
    usage: /helloworld