name: CommunityMinecraftPlugin
main: io.github.communityminecraftplugin.communityminecraftplugin.Core
version: ${project.version}
description: Hello world!
commands:
  helloworld:
    description: Hello, world!
    usage: /helloworld